### ISSUE TITLE
Лабораторная работа №2

### ISSUE THREAD

**Issue by trtpo** [avasilevich/trtpoEKB#3]
Артём, не вижу у Вас соответствия между документом и мокапами :( Например, у Вас есть картинка для SignUp, но в функциональных требованиях об этом вообще ничего нет. И наоборот - в требованиях написано, что "Страницы преподавателей должны иметь отображаемое расписание занятий", а картинки про это нет.
Далее, поясните в документе, что такое "Возможность online просмотра файлов типа *.pdf без загрузки". Загрузки куда? Он же будет в страничке загружаться, как иначе Ваш пользователь сможет его просматривать ;)
По нефункциональным требованиям: не принимаю требование "Расширяемость" - не понятно, как продемонстрировать его выполнение. Функциональные требования меняться не будут!

**Comment by avasilevich** [comment]
Обновлено!
